### ISSUE TITLE
Room Permissions

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#204]
### Prerequisites
- [x] Requires #50 to be completed first.

# Requirements

### Available permissions
Each bullet point should be it's own permission. Adding new permissions should not invalidate all old permissions. No conversion process (eg a migration) should be required when adding a new permission.
- Playback Control
    - Play/pause
    - Skip
    - Seek
- Queue Management
    - Add to queue
    - Remove from queue
    - Change the order of videos in queue (manual queue mode)
    - Vote for existing videos in queue (voting queue mode)
- Chat
- Configure Room
    - Modify title
    - Modify description
    - Modify visibility
    - Modify queue mode
    - Modify permissions
        - For Moderator
        - For Trusted User
        - For All registered users
        - For All unregistered users
- User Management
    - Promote to Administrator _(hidden, granted only to administrators)_
    - Demote Administrator _(hidden, granted only to room owner)_
    - Promote to Moderator
    - Demote Moderator
    - Promote to Trusted User
    - Demote Trusted User

### Roles

All preset and generic roles should be in a strict hierarchy, in the order they are listed here, from most to least powerful.

3 preset roles (only available for permanent rooms)
- Administrator
    - Owner automatically given this role, can't be removed from owner
    - Gives permission to everything, cannot and should not be modifiable to prevent users locking themselves out
- Moderator
- Trusted User

2 generic roles
- All registered users
- All unregistered users

## Mechanics

Preset roles are only available to permanent rooms. Temporary rooms can only configure the 2 generic roles. _Maybe it would be a good idea to be able to keep track of the owner of a temporary room?_

In temporary rooms, by default, Playback Control, Queue Management, Chat, and Configure Room are granted to all roles.

In permanent rooms, by default, Playback Control, Queue Management, Chat, and Configure Room (minus Modify permissions) are granted to all roles. As a result, in order to promote a user to higher roles, someone must claim ownership of the room.

### Behavior

All permissions granted to lesser roles should be automatically granted to higher roles. For example, if all unregistered users are granted Chat, then by extension, all registered users are granted Chat.

While it can remain possible for users to demote themselves, they should be warned before doing so to prevent accidents.

### Restrictions

Since all preset and generic roles should be in a strict hierarchy, it should not be possible for Trusted User to be more powerful than Moderator.

It should never be possible for users to promote themselves more powerful roles, or to configure permissions to allow this. Conversely, it should not be possible to demote more powerful users, or to configure permissions to allow this. Therefore:
- Moderators can _never_ have
    - Modify permissions (For Moderator)
- Trusted Users can _never_ have
    - Promote to Moderator
    - Demote Moderator
    - Modify permissions (For Moderator, and For Trusted User)
- Both generic roles can _never_ have
    - Promote to Moderator
    - Demote Moderator
    - Promote to Trusted User
    - Demote Trusted User
    - Modify permissions

## Todo

- [x] Client: UI for editing permissions
- [x] Server: Check for permission before acting on user requests
- [x] Server: Persistent storage for room permission configuration
- [x] Server: Persistent storage for roles that users have for each room
- [x] Unit Tests
- [ ] Rigorous user testing to minimize potential exploits
