### ISSUE TITLE
Allow users to create permanent rooms, even though we don't have user accounts yet

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#234]
We have a lot of returning users, and requesting me to make permanent rooms via twitter DMs isn't really ideal. We are going to allow users to "claim" permanent rooms anyway when we add user accounts, so it makes sense to allow creation of permanent rooms.

## TODO
- [x] Client: Add page/form to create permanent rooms.
- [x] Client: Notify returning users that they can create permanent rooms via notification? tooltip?
- [x] Client: Update FAQ
- [x] Server: Rate limit room create endpoint to minimize potential spam
- [x] Server: Limit room name length to a reasonable number
