### ISSUE TITLE
3 small bugs/issues I found.

### ISSUE THREAD

**Issue by XeroxDev** [dyc3/opentogethertube#271]
I found 3 Issues. I put all 3 in one issue, cause of issue spamming and cause of that, I visualize these as tasks so you can mark them, if you sit on these tasks :D

## Current Behavior
- **Join-Notification Snackbar**: The Join-Notification Snackbar pops up repeatedly in unspecific interval. This means: I join a room. Watch Videos and get in random interval the Join-Notification of me or other users displayed.
- **Fullscreen Scrollbar**: If you go into fullscreen mode (with F or Fullscreen button from the site) the scrollbar is still visible. It's not a hard bug, but it's not real fullscreen either :D
- **Claim Room**: If you claimed your room, with your account, after a unspecific amount of time / browser closed / cleared cache, you can / need to claim the room again.

### How To Reproduce
- **Join-Notification Snackbar**: Just watch Videos and wait. Maybe it's cause of a short connection loss due SocketIO?
- **Fullscreen Scrollbar**: Just go into fullscreen mode. Little css tweaks and it's fixed :D
- **Claim Room**: Unknown how to reproduce it to 100% but I noticed it multiple times, after I went to my room again after some time / next day and looked into settings.

## Expected behavior
- **Join-Notification Snackbar**: Just show the Snackbar, if the user really joined the room.
- **Fullscreen Scrollbar**: Scrollbar should be disabled or invisible (if you want to allow the user to scroll like in youtube videos) in fullscreen.
- **Claim Room**: Should stay claimed.

## Environment
- [ ] This happens on the official site: opentogethertube.com (not tested)
- [X] This happens using a self-hosted version.

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox & Chrome
 - Version: FF 77.0.1 | Chrome 83.0.4103.106

#### Additional context
It's not that important, but should be improved :D I would help you, but I don't know anything about vue, I'm a Angular guy :D 

But still. Nice work! Keep on it. Your project has potential!

#### Tasks-Overview
- [ ] Join-Notification Snackbar
- [ ] Fullscreen Scrollbar
- [ ] Claim Room

**Comment by dyc3** [comment]
I'd prefer if you put these into 3 different issues

**Comment by XeroxDev** [comment]
I'll created the 3 issues
Snackbar #272 
Scrollbar #273
Claim Room #274
